import data from "./redistricting-2026.json";

/**
 * States whose 2026 congressional map differs from the 119th Congress outlines
 * drawn on the map. Generated by `npm run build:redistricting` from Geocodio's
 * cd120 data; see public/geo/SOURCES.md.
 */
export const REDISTRICTED_STATES: ReadonlySet<string> = new Set(Object.keys(data.states));

export function isRedistricted(state: string | null | undefined) {
  return Boolean(state && REDISTRICTED_STATES.has(state));
}
